<?php
	// global settings
	$ocdi_fields_to_change = array(
		'options_global_footer_show_logo' => '1',
		'_options_global_footer_show_logo' => 'field_57e28efb2fc28',
		'options_global_footer_logo_type' => 'image',
		'options_global_footer_logo_font_family' => 'a:3:{s:4:"font";s:10:"Montserrat";s:8:"variants";a:2:{i:0;s:7:"regular";i:1;s:3:"700";}s:7:"subsets";a:1:{i:0;s:5:"latin";}}',
		'_options_global_footer_logo_font_family' => 'field_57f36d64266f8',
		'options_global_footer_show_copyright' => '0',
		'_options_global_footer_show_copyright' => 'field_57e292c889265',
		'options_global_footer_copyright_text' => '&copy; 2020, Argenta theme by <a href="https://clbthemes.com" target="_blank">Colabrio</a>',
		'options_global_header_menu_style' => 'style6',
		'options_global_logo_type' => 'image',
		'options_global_header_menu_logo_font' => 'a:3:{s:4:"font";s:10:"Montserrat";s:8:"variants";a:2:{i:0;s:7:"regular";i:1;s:3:"700";}s:7:"subsets";a:1:{i:0;s:5:"latin";}}',
		'_options_global_header_menu_logo_font' => 'field_57e277579ea3d',
		'options_global_header_menu_background_color' => '#343436',
		'options_global_header_menu_text_color' => '#ffffff',
		'options_global_header_menu_border_color' => '#8c8c8c',
		'options_global_header_menu_border_type' => 'dotted',
		'options_global_header_menu_hide_contacts_bar' => '1',
		'options_global_header_menu_contacts_bar_phone_numbers' => '1',
		'options_global_header_menu_contacts_bar_emails' => '1',
		'options_global_header_menu_contacts_bar_additional' => 'Work time: 9:00 - 20:00',
		'options_global_header_menu_contacts_bar_social_links' => '5',
		'options_global_header_menu_contacts_bar_text_color' => '',
		'_options_global_header_menu_contacts_bar_text_color' => 'field_57e2486335390',
		'options_global_header_use_hero' => '1',
		'options_global_header_tilte_color' => '',
		'_options_global_header_tilte_color' => 'field_57e8c4e007124',
		'options_global_logo_image' => '',
		'_options_global_logo_image' => 'field_59229bda32f63',
		'options_global_page_favicon' => '2204',
		'_options_global_page_favicon' => 'field_57e3941edf6d9',
		'options_global_page_main_font_family' => 'a:3:{s:4:"font";s:9:"Open Sans";s:8:"variants";a:3:{i:0;s:7:"regular";i:1;s:3:"600";i:2;s:3:"700";}s:7:"subsets";a:1:{i:0;s:5:"latin";}}',
		'_options_global_page_main_font_family' => 'field_57e38bc429f0d',
		'options_global_page_titles_font_family' => 'a:3:{s:4:"font";s:10:"Montserrat";s:8:"variants";a:2:{i:0;s:7:"regular";i:1;s:3:"700";}s:7:"subsets";a:1:{i:0;s:5:"latin";}}',
		'_options_global_page_titles_font_family' => 'field_57e38bff29f0e',
		'options_global_page_is_wrapped' => '0',
		'options_global_header_menu_contacts_bar_phone_numbers_0_phone_numbers' => '+43 069 905 670 50',
		'_options_global_header_menu_contacts_bar_phone_numbers_0_phone_numbers' => 'field_59229bda6c954',
		'options_global_header_menu_contacts_bar_social_links_0_social_network' => 'facebook',
		'_options_global_header_menu_contacts_bar_social_links_0_social_network' => 'field_59229bda7b686',
		'options_global_header_menu_contacts_bar_social_links_0_url' => 'https://www.facebook.com/',
		'_options_global_header_menu_contacts_bar_social_links_0_url' => 'field_59229bda7ba5a',
		'options_global_header_menu_contacts_bar_social_links_1_social_network' => 'twitter',
		'_options_global_header_menu_contacts_bar_social_links_1_social_network' => 'field_59229bda7b686',
		'options_global_header_menu_contacts_bar_social_links_1_url' => 'https://twitter.com/',
		'_options_global_header_menu_contacts_bar_social_links_1_url' => 'field_59229bda7ba5a',
		'options_global_header_menu_contacts_bar_social_links_2_social_network' => 'googleplus',
		'_options_global_header_menu_contacts_bar_social_links_2_social_network' => 'field_59229bda7b686',
		'options_global_header_menu_contacts_bar_social_links_2_url' => 'https://plus.google.com/',
		'_options_global_header_menu_contacts_bar_social_links_2_url' => 'field_59229bda7ba5a',
		'options_global_header_menu_contacts_bar_social_links_3_social_network' => 'instagram',
		'_options_global_header_menu_contacts_bar_social_links_3_social_network' => 'field_59229bda7b686',
		'options_global_header_menu_contacts_bar_social_links_3_url' => 'https://www.instagram.com/',
		'_options_global_header_menu_contacts_bar_social_links_3_url' => 'field_59229bda7ba5a',
		'options_global_header_menu_contacts_bar_emails_0_emails' => 'argenta.sales@mail.com',
		'_options_global_header_menu_contacts_bar_emails_0_emails' => 'field_59229bda725e5',
		'options_global_footer_logo_image' => '2152',
		'_options_global_footer_logo_image' => 'field_57f35f35deb92',
		'options_global_footer_is_wrapped' => '0',
		'options_global_logo_image_second' => '2153',
		'_options_global_logo_image_second' => 'field_57e2685a24b198f1',
		'options_global_header_menu_fixed' => '1',
		'options_global_page_show_breadcrumbs' => '0',
		'options_global_page_show_arrow' => '0',
		'options_global_project_hide_breadcrumbs' => '0',
		'options_global_portfolio_page' => '471',
		'options_global_footer_hide' => '1',
		'options_global_header_menu_add_cap' => 'no',
		'options_global_woocommerce_header_menu_hide_border' => 'inherit',
		'_options_global_woocommerce_header_menu_hide_border' => 'field_57e9090dab86a_woo',
		'options_global_woocommerce_header_menu_border_color' => '',
		'_options_global_woocommerce_header_menu_border_color' => 'field_57e24486ad548_woo',
		'options_global_woocommerce_header_menu_border_type' => 'inherit',
		'_options_global_woocommerce_header_menu_border_type' => 'field_57e273850bfe3_woo',
		'options_global_woocommerce_header_background_image' => '4559',
		'_options_global_woocommerce_header_background_image' => 'field_57dfa3f8e9525_woo',
		'options_global_woocommerce_header_background_size' => 'cover',
		'_options_global_woocommerce_header_background_size' => 'field_57dfd77f67f25_woo',
		'options_global_woocommerce_header_overlay_color' => '#404042',
		'options_global_woocommerce_header_use_hero' => '0',
		'options_global_woocommerce_page_show_breadcrumbs' => 'yes',
		'options_global_woocommerce_page_is_wrapped' => 'yes',
		'options_global_page_subtitles_font_family' => 'a:3:{s:4:"font";s:4:"Lora";s:8:"variants";a:4:{i:0;s:7:"regular";i:1;s:6:"italic";i:2;s:3:"700";i:3;s:9:"700italic";}s:7:"subsets";a:5:{i:0;s:5:"latin";i:1;s:8:"cyrillic";i:2;s:9:"latin-ext";i:3;s:10:"vietnamese";i:4;s:12:"cyrillic-ext";}}',
		'_options_global_page_subtitles_font_family' => 'field_57e38bff29f0e__',
		'options_global_page_add_top_padding' => '0',
		'options_global_page_smooth_scroll' => '1',
		'options_global_page_headings_color' => '',
		'_options_global_page_headings_color' => 'field_57e3906e7b521head',
		'options_global_header_menu_contacts_bar_social_links_4_social_network' => 'dribbble',
		'_options_global_header_menu_contacts_bar_social_links_4_social_network' => 'field_59229bda7b686',
		'options_global_header_menu_contacts_bar_social_links_4_url' => 'https://www.instagram.com/',
		'_options_global_header_menu_contacts_bar_social_links_4_url' => 'field_59229bda7ba5a',
		'options_global_page_text_typo' => '{"font_family":"Open Sans","font_variants":["700italic","700","italic","regular"],"font_subsets":["latin-ext","latin"]}',
		'options_global_page_headings_typo' => '{"font_family":"Montserrat","font_variants":["900italic","900","700italic","700","600italic"],"font_subsets":["latin-ext","latin"]}',
		'options_global_page_subtitles_typo' => '{"font_family":"Lora","font_variants":["italic","regular"],"font_subsets":["latin-ext","latin"]}',
		'options_global_logo_image_light' => '2152',
		'_options_global_logo_image_light' => 'field_5936b2dd92771',
		'options_global_logo_image_light_retina' => '',
		'_options_global_logo_image_light_retina' => 'field_5936b357132bf',
		'options_global_logo_image_light_mobile' => '',
		'_options_global_logo_image_light_mobile' => 'field_5936b371132c0',
		'options_global_logo_image_dark' => '2153',
		'_options_global_logo_image_dark' => 'field_5936af24f4b7e',
		'options_global_logo_image_dark_retina' => '',
		'_options_global_logo_image_dark_retina' => 'field_5936afd421bba',
		'options_global_logo_image_dark_mobile' => '',
		'_options_global_logo_image_dark_mobile' => 'field_5936affb21bbb',
		'options_global_logo_image_dark_variant' => '',
		'_options_global_logo_image_dark_variant' => 'field_5936add283a9a',
		'options_global_header_logo_by_default' => 'light_variant',
		'_options_global_header_logo_by_default' => 'field_5937e1905d075',
		'options_global_header_logo_when_fixed' => 'light_variant',
		'_options_global_header_logo_when_fixed' => 'field_5937e1905d075_fixed',
		'options_global_header_menu_text_typo' => '{"color":"#ffffff"}',
		'options_global_header_tilte_align' => 'left',
		'_options_global_header_tilte_align' => 'field_59229e431eaea',
		'options_global_page_custom_css' => '
#masthead .socialbar a {
   background: #c3c3c3;
   color: #343436;
}
#masthead .socialbar a:hover {
   background: transparent;
   color: #c3c3c3;
}

header.header-6 .menu-other::after,
header.header-6 .main-nav::after {
border-top: 1px solid rgba(255,255,255, 0.1);
}'
	);